var dir_00b70934845ca21c87ee2bbcaca3c7ca =
[
    [ "dev", "dir_51fc4b939acd53a9324bc733e46d1ff4.html", "dir_51fc4b939acd53a9324bc733e46d1ff4" ],
    [ "test", "dir_97b10fb38c2279ba8c473801fa5e757b.html", "dir_97b10fb38c2279ba8c473801fa5e757b" ],
    [ "yaml", "dir_8c5ede79dcee85044b81e7a159dd7d73.html", "dir_8c5ede79dcee85044b81e7a159dd7d73" ],
    [ "barycentricInterpolation.cpp", "barycentric_interpolation_8cpp.html", "barycentric_interpolation_8cpp" ],
    [ "cartesian2cylindricalmex.cpp", "cartesian2cylindricalmex_8cpp.html", "cartesian2cylindricalmex_8cpp" ],
    [ "closestExpmapmex.cpp", "closest_expmapmex_8cpp.html", "closest_expmapmex_8cpp" ],
    [ "convexHull.cpp", "convex_hull_8cpp.html", "convex_hull_8cpp" ],
    [ "convexHull.h", "convex_hull_8h.html", "convex_hull_8h" ],
    [ "cylindrical2cartesianmex.cpp", "cylindrical2cartesianmex_8cpp.html", "cylindrical2cartesianmex_8cpp" ],
    [ "drakeAppUtil.h", "drake_app_util_8h.html", "drake_app_util_8h" ],
    [ "drakeDebugMex.cpp", "drake_debug_mex_8cpp.html", "drake_debug_mex_8cpp" ],
    [ "drakeGeometryUtil.cpp", "drake_geometry_util_8cpp.html", "drake_geometry_util_8cpp" ],
    [ "drakeGeometryUtil.h", "drake_geometry_util_8h.html", "drake_geometry_util_8h" ],
    [ "drakeGradientUtil.h", "drake_gradient_util_8h.html", "drake_gradient_util_8h" ],
    [ "drakeMexUtil.cpp", "drake_mex_util_8cpp.html", "drake_mex_util_8cpp" ],
    [ "drakeMexUtil.h", "drake_mex_util_8h.html", "drake_mex_util_8h" ],
    [ "drakeUtil.cpp", "drake_util_8cpp.html", "drake_util_8cpp" ],
    [ "drakeUtil.h", "drake_util_8h.html", "drake_util_8h" ],
    [ "eigen_matrix_compare.h", "eigen__matrix__compare_8h.html", "eigen__matrix__compare_8h" ],
    [ "expmap2quatImplmex.cpp", "expmap2quat_implmex_8cpp.html", "expmap2quat_implmex_8cpp" ],
    [ "flipExpmapmex.cpp", "flip_expmapmex_8cpp.html", "flip_expmapmex_8cpp" ],
    [ "getKey.cpp", "get_key_8cpp.html", "get_key_8cpp" ],
    [ "lcmLogger.cpp", "lcm_logger_8cpp.html", "lcm_logger_8cpp" ],
    [ "LCMScope.h", "_l_c_m_scope_8h.html", [
      [ "LCMScope", "class_l_c_m_scope.html", "class_l_c_m_scope" ]
    ] ],
    [ "lcmUtil.cpp", "lcm_util_8cpp.html", "lcm_util_8cpp" ],
    [ "lcmUtil.h", "lcm_util_8h.html", "lcm_util_8h" ],
    [ "makeFunction.h", "make_function_8h.html", "make_function_8h" ],
    [ "mexify.h", "mexify_8h.html", "mexify_8h" ],
    [ "MexWrapper.cpp", "_mex_wrapper_8cpp.html", null ],
    [ "MexWrapper.h", "_mex_wrapper_8h.html", "_mex_wrapper_8h" ],
    [ "Polynomial.cpp", "_polynomial_8cpp.html", "_polynomial_8cpp" ],
    [ "Polynomial.h", "_polynomial_8h.html", "_polynomial_8h" ],
    [ "publishLCMLog.cpp", "publish_l_c_m_log_8cpp.html", "publish_l_c_m_log_8cpp" ],
    [ "quat2expmapmex.cpp", "quat2expmapmex_8cpp.html", "quat2expmapmex_8cpp" ],
    [ "quat2expmapSequencemex.cpp", "quat2expmap_sequencemex_8cpp.html", "quat2expmap_sequencemex_8cpp" ],
    [ "realtime.cpp", "realtime_8cpp.html", "realtime_8cpp" ],
    [ "resolveCenterOfPressuremex.cpp", "resolve_center_of_pressuremex_8cpp.html", "resolve_center_of_pressuremex_8cpp" ],
    [ "standardMexConversions.h", "standard_mex_conversions_8h.html", "standard_mex_conversions_8h" ],
    [ "testUtil.h", "test_util_8h.html", "test_util_8h" ],
    [ "TrigPoly.h", "_trig_poly_8h.html", "_trig_poly_8h" ],
    [ "unwrapExpmapmex.cpp", "unwrap_expmapmex_8cpp.html", "unwrap_expmapmex_8cpp" ]
];